# Generated by Django 2.1.7 on 2019-04-05 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime(2019, 4, 5, 11, 54, 56, 812768)),
        ),
    ]
